name: jaspr_tailwind
description: Tailwind integration for Jaspr.
<<<<<<< HEAD
version: 0.4.0
=======
version: 0.3.3
>>>>>>> 5fff142fdb5c06a6e74449048a7ab20230f770d9
repository: https://github.com/dinko7/jaspr_tailwind/
issue_tracker: https://github.com/dinko7/jaspr_tailwind/issues
documentation: https://docs.jaspr.site/eco/tailwind

topics:
  - jaspr
  - web
  - html
  - css

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
<<<<<<< HEAD
  build: ^3.1.0
=======
  build: ^2.0.0
>>>>>>> 5fff142fdb5c06a6e74449048a7ab20230f770d9
  build_modules: ^5.0.4
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^3.0.0
